// Generated by dbc-lab for preset "stock-pair-usdc". Review every value before signing anything.
// Usage:  RPC_URL=https://api.devnet.solana.com KEYPAIR=./partner.json npx tsx create-config.ts
import { NATIVE_MINT } from "@solana/spl-token";
import { Connection, Keypair, PublicKey } from "@solana/web3.js";
import BN from "bn.js";
import fs from "node:fs";
import { DynamicBondingCurveClient } from "@meteora-ag/dynamic-bonding-curve-sdk";

// BN values are stored as {"$bn": "<decimal>"} in config-parameters.json
const params = JSON.parse(fs.readFileSync("./config-parameters.json", "utf8"), (_k, v) =>
  v && typeof v === "object" && typeof v.$bn === "string" ? new BN(v.$bn, 10) : v,
);

const connection = new Connection(process.env.RPC_URL!, "confirmed");
const client = DynamicBondingCurveClient.create(connection, "confirmed");
const partner = Keypair.fromSecretKey(Uint8Array.from(JSON.parse(fs.readFileSync(process.env.KEYPAIR!, "utf8"))));
const config = Keypair.generate();

const tx = await client.partner.createConfig({
  config: config.publicKey,
  feeClaimer: partner.publicKey,
  leftoverReceiver: partner.publicKey,
  payer: partner.publicKey,
  quoteMint: new PublicKey(process.env.QUOTE_MINT!),
  ...params,
});
tx.feePayer = partner.publicKey;
tx.recentBlockhash = (await connection.getLatestBlockhash()).blockhash;
tx.sign(partner, config);
const sig = await connection.sendRawTransaction(tx.serialize());
console.log("config", config.publicKey.toBase58(), "tx", sig);
